var easyTimer=30;
var moderateTimer = 45;
var hardTimer=60;

var easy = [
"bribery",
"trojan horse",
"key control",
"corruption",
"authentication",
"cybersecurity",
"guidelines",
"layering",
"pharming",
"phishing",
"hazard",
"prevention",
"audit services",
"confidential",
"encryption",
"archer",
"fraud",
"report"
];

var easyLetters = [
"briberyingft",
"trojanhorsevirus",
"keycontrolisknga",
"corruptionolica",
"authenticationate",
"cybersecuritynnts",
"guidelinescompa",
"layeringsian",
"pharmingfast",
"phishingfsin",
"hazardouis",
"preventionivect",
"auditservicesing",
"confidentialsecrs",
"encryptionlocks",
"archerysin",
"fraudsakei",
"reportcall"
];

var moderate = ["alert",
"audit report",
"fictitious",
"hacking",
"identity theft",
"intermediary",
"malware",
"monitor",
"piracy",
"profile",
"risk",
"security",
"source of fund",
"suspicious",
"terrorist"];

var moderateLetters = ["alertmsi",
"audit reportmeeng",
"fictitiousaenrs",
"hackingyber",
"identitytheftstela",
"intermediarybggas",
"malwarevsui",
"monitoracea",
"piracytesn",
"profileogns",
"riskcare",
"securitygadkn",
"sourceoffundmoneys",
"suspiciousmfngr",
"terroristmingw"];

var hard = ["unusual",
"due diligence",
"legitimate",
"skimming",
"know your customer",
"social engineering",
"authority",
"spamming",
"scamming",
"spoofing",
"ransomware",
"conflict of interest",
"investigation",
"evil twins"];

var hardLetters = ["unusualqiesn",
"duediligencefitras",
"legitimateornas",
"skimmingteall",
"knowyourcustomerlientcenr",
"socialengineeringdiams",
"authorityledng",
"spammingeails",
"scammingteall",
"spoofinghacks",
"ransomwarevusl",
"conflictofinterestjulagus",
"investigationdecis",
"eviltwinsruaei"];